ALTER TABLE loan ADD COLUMN monthly_repayment_day INTEGER NOT NULL DEFAULT 0;

ALTER TABLE repayment ADD COLUMN is_early_repayment INTEGER NOT NULL DEFAULT 0;
ALTER TABLE repayment ADD COLUMN period INTEGER DEFAULT NULL;
