-- todo
CREATE TABLE `todo` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `uid` VARCHAR(256) NOT NULL UNIQUE,
  `creator_id` INT NOT NULL,
  `created_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `title` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `due_time` TIMESTAMP NOT NULL,
  `priority` VARCHAR(256) NOT NULL DEFAULT 'LOW',
  `status` VARCHAR(256) NOT NULL DEFAULT 'NORMAL',
  `payload` TEXT NOT NULL
);
